@file:Suppress("unused")

package im.tony.types.drivemodels

data class DriveModelAbout(val value: com.google.api.services.drive.model.About)
data class DriveModelChange(val value: com.google.api.services.drive.model.Change)
data class DriveModelChangeList(val value: com.google.api.services.drive.model.ChangeList)
data class DriveModelChannel(val value: com.google.api.services.drive.model.Channel)
data class DriveModelComment(val value: com.google.api.services.drive.model.Comment)
data class DriveModelCommentList(val value: com.google.api.services.drive.model.CommentList)
data class DriveModelContentRestriction(val value: com.google.api.services.drive.model.ContentRestriction)
data class DriveModelDrive(val value: com.google.api.services.drive.model.Drive)
data class DriveModelDriveList(val value: com.google.api.services.drive.model.DriveList)
data class DriveModelFile(val value: com.google.api.services.drive.model.File)
data class DriveModelFileList(val value: com.google.api.services.drive.model.FileList)
data class DriveModelGeneratedIds(val value: com.google.api.services.drive.model.GeneratedIds)
data class DriveModelPermission(val value: com.google.api.services.drive.model.Permission)
data class DriveModelPermissionList(val value: com.google.api.services.drive.model.PermissionList)
data class DriveModelReply(val value: com.google.api.services.drive.model.Reply)
data class DriveModelReplyList(val value: com.google.api.services.drive.model.ReplyList)
data class DriveModelRevision(val value: com.google.api.services.drive.model.Revision)
data class DriveModelRevisionList(val value: com.google.api.services.drive.model.RevisionList)
data class DriveModelStartPageToken(val value: com.google.api.services.drive.model.StartPageToken)
data class DriveModelTeamDrive(val value: com.google.api.services.drive.model.TeamDrive)
data class DriveModelTeamDriveList(val value: com.google.api.services.drive.model.TeamDriveList)
data class DriveModelUser(val value: com.google.api.services.drive.model.User)
